name:                pacman-main
version:             0.1.0.0
github:              "fskroes/pacman-main"
license:             BSD-3-Clause
author:              "Fernando Silva Kroes"
maintainer:          "fskroes@outlook.com"
copyright:           "MIT"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fskroes/pacman-main#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- aeson
- text
- bytestring
- containers
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pacman-main-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pacman-main

tests:
  pacman-main-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pacman-main
    - QuickCheck
    - hspec
